FROM node:18-alpine

WORKDIR /app

# Instalar dependencias
COPY package*.json ./
RUN npm install

# Copiar código fuente
COPY . .

EXPOSE 3001

ENV PORT 3001

# Comando para desarrollo con hot reload
CMD ["npm", "run", "dev"]
